### ISSUE TITLE
Where is ProgressView?

### ISSUE THREAD

**Issue by micky2be** [sidneys/cordova-plugin-progressview#3]
Could be nice to mention in the documentation where we can find the object ProgressView.

Apparently it's under `window.plugins`

**Comment by NickBolles** [comment]
This is standard for all Cordova Plugins. But wouldn't hurt to mention

**Comment by micky2be** [comment]
It's more a default than a standard I fear (2 out of 10 plugins I use behave like this, including yours).
If not `window.plugins`, at least mentioned that it is exposed by the standard of Cordova plugins :wink:
